name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_12.1.app

    - name: Install Dependencies
      run: |
        cd GithubSwift
        pod install --repo-update

    - name: Build and test
      run: xcodebuild clean build test -scheme GithubSwift/GithubSwift -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.1'

